version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
    groups:
      npm-production:
        dependency-type: "production"
      npm-development:
        dependency-type: "development"
ignore:
  - dependency-name: "@types/node*"
    versions: [ ">=24" ]
