import { defineConfig } from "tsup";

// NOTE: array configs build CONCURRENTLY and `clean: true` wipes the whole
// outDir, so cleaning lives in the `prebuild` script (run/clean-dist.mjs).
// `target` is intentionally unset: tsup reads es2022 from tsconfig.json.
export default defineConfig([
	{
		entry: ["src/index.ts"],
		format: ["cjs", "esm"],
		dts: true,
		clean: false,
	},
	{
		entry: { cli: "src/cli.ts" },
		format: ["cjs"],
		dts: false,
		clean: false,
		// npm's Windows bin shims are generated by parsing this shebang, and
		// npm chmods bin targets on POSIX — no chmod step needed here.
		banner: { js: "#!/usr/bin/env node" },
		// The mcp subcommand lazy-requires the built sibling via package
		// self-reference; keeping it external keeps the CLI bundle tiny and
		// free of the ts-morph/SDK graph.
		external: ["playwright-page-object/mcp"],
	},
	{
		entry: { mcp: "src/mcp/index.ts" },
		format: ["cjs", "esm"],
		dts: true,
		clean: false,
		// `readVersion` reads `__dirname`, which does not exist in an ESM module:
		// the reference threw, the `try` swallowed it, and every server created
		// through the ESM condition of `playwright-page-object/mcp` advertised
		// version 0.0.0 in the MCP handshake while the CJS one advertised the real
		// number. `run/verify-dist.mjs` now boots both and compares, because
		// nothing about the source says which format it is being read from.
		shims: true,
		// Runtime dependencies stay external (tsup default for `dependencies`);
		// spelled out here as documentation-in-code.
		external: ["@modelcontextprotocol/server", "ts-morph", "zod"],
	},
]);
