import { defineConfig } from "tsup";

// NOTE: array configs build CONCURRENTLY and `clean: true` wipes the whole
// outDir, so cleaning lives in the `prebuild` script (run/clean-dist.mjs).
// `target` is intentionally unset: tsup reads es2022 from tsconfig.json.
export default defineConfig([
	{
		entry: ["src/index.ts"],
		format: ["cjs", "esm"],
		dts: true,
		clean: false,
	},
	{
		entry: { cli: "src/cli.ts" },
		format: ["cjs"],
		dts: false,
		clean: false,
		// npm's Windows bin shims are generated by parsing this shebang, and
		// npm chmods bin targets on POSIX — no chmod step needed here.
		banner: { js: "#!/usr/bin/env node" },
	},
]);
