name: Publish Package
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write 
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true
      - uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check Formatting & Linting
        run: npm run lint

      - name: Build
        run: npm run build
        
      - name: Run Tests
        run: npm run test

      - name: Test Example
        run: npm run test:example
        
      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
        run: npx semantic-release